#!/bin/bash
# Port allocation utilities for worktrees
# Each worktree gets a unique port pair based on its index

# Base ports (main worktree uses these)
BASE_BACKEND_PORT=8000
BASE_FRONTEND_PORT=5173

# Port increment per worktree (adds 10 for each worktree)
# This gives us ports like:
#   Main:       8000, 5173
#   Worktree 1: 8010, 5183
#   Worktree 2: 8020, 5193
#   etc.
PORT_INCREMENT=10

# Get the worktree index (0 for main, 1+ for worktrees)
get_worktree_index() {
    local current_path="$1"
    local worktree_base="/home/george_cairns/code/rightplace-worktrees"
    local main_repo="/home/george_cairns/code/rightplace"
    
    # If in main repo, index is 0
    if [[ "$current_path" == "$main_repo"* && "$current_path" != "$worktree_base"* ]]; then
        echo 0
        return
    fi
    
    # Otherwise, calculate index from worktree name
    # List all worktrees sorted by name, find our position
    local worktree_name=$(basename "$current_path")
    local index=1
    
    for wt in $(ls "$worktree_base" 2>/dev/null | sort); do
        if [ "$wt" == "$worktree_name" ]; then
            echo $index
            return
        fi
        ((index++))
    done
    
    # New worktree, assign next available index
    echo $index
}

# Calculate ports for a worktree
calculate_ports() {
    local worktree_path="$1"
    local index=$(get_worktree_index "$worktree_path")
    
    local backend_port=$((BASE_BACKEND_PORT + (index * PORT_INCREMENT)))
    local frontend_port=$((BASE_FRONTEND_PORT + (index * PORT_INCREMENT)))
    
    echo "$backend_port $frontend_port"
}

# Create .worktree.env file with port configuration
create_worktree_env() {
    local worktree_path="$1"
    local ports=$(calculate_ports "$worktree_path")
    local backend_port=$(echo $ports | cut -d' ' -f1)
    local frontend_port=$(echo $ports | cut -d' ' -f2)
    local worktree_name=$(basename "$worktree_path")
    
    cat > "$worktree_path/.worktree.env" << EOF
# Worktree-specific configuration
# Auto-generated by worktree-new.sh

WORKTREE_NAME=$worktree_name
BACKEND_PORT=$backend_port
FRONTEND_PORT=$frontend_port
VITE_API_URL=http://localhost:$backend_port/api/v1
EOF
    
    echo "Created .worktree.env with ports: backend=$backend_port, frontend=$frontend_port"
}

# Read port configuration for current directory
get_ports() {
    local script_dir="$(pwd)"
    local env_file=""
    
    # Look for .worktree.env in current dir or parent dirs
    local check_dir="$script_dir"
    while [ "$check_dir" != "/" ]; do
        if [ -f "$check_dir/.worktree.env" ]; then
            env_file="$check_dir/.worktree.env"
            break
        fi
        check_dir=$(dirname "$check_dir")
    done
    
    if [ -f "$env_file" ]; then
        source "$env_file"
        echo "$BACKEND_PORT $FRONTEND_PORT"
    else
        # Default to main ports
        echo "$BASE_BACKEND_PORT $BASE_FRONTEND_PORT"
    fi
}

# Show all allocated ports
show_port_allocations() {
    local main_repo="/home/george_cairns/code/rightplace"
    local worktree_base="/home/george_cairns/code/rightplace-worktrees"
    
    echo "Port Allocations:"
    echo ""
    printf "%-30s %-12s %-12s\n" "Worktree" "Backend" "Frontend"
    printf "%-30s %-12s %-12s\n" "--------" "-------" "--------"
    
    # Main repo
    if [ -f "$main_repo/.worktree.env" ]; then
        source "$main_repo/.worktree.env"
        printf "%-30s %-12s %-12s\n" "MAIN" "$BACKEND_PORT" "$FRONTEND_PORT"
    else
        printf "%-30s %-12s %-12s\n" "MAIN" "$BASE_BACKEND_PORT" "$BASE_FRONTEND_PORT"
    fi
    
    # Other worktrees
    if [ -d "$worktree_base" ]; then
        for wt_dir in "$worktree_base"/*/; do
            if [ -d "$wt_dir" ]; then
                wt_name=$(basename "$wt_dir")
                if [ -f "$wt_dir/.worktree.env" ]; then
                    source "$wt_dir/.worktree.env"
                    printf "%-30s %-12s %-12s\n" "$wt_name" "$BACKEND_PORT" "$FRONTEND_PORT"
                fi
            fi
        done
    fi
}

# If script is run directly, show port allocations
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    show_port_allocations
fi
