#!/bin/bash
# Port allocation utilities for worktrees
# Each worktree gets a unique port pair based on its index

# Base ports (main worktree uses these)
BASE_BACKEND_PORT=8000
BASE_FRONTEND_PORT=5173

# Port increment per worktree (adds 10 for each worktree)
# This gives us ports like:
#   Main:       8000, 5173
#   Worktree 1: 8010, 5183
#   Worktree 2: 8020, 5193
#   etc.
PORT_INCREMENT=10

# Script/Repo discovery
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Default worktree base can be overridden via environment variable WORKTREE_BASE.
if [ -z "$WORKTREE_BASE" ]; then
    case "$(uname -s)" in
        CYGWIN*|MINGW*|MSYS*)
            WORKTREE_BASE="$USERPROFILE\\code\\rightplace-worktrees"
            ;;
        *)
            WORKTREE_BASE="$HOME/code/rightplace-worktrees"
            ;;
    esac
fi

# Default main repo path. Can be overridden with MAIN_REPO env var.
if [ -z "$MAIN_REPO" ]; then
    MAIN_REPO="$REPO_ROOT"
fi

# Print derived configuration when script is executed directly
print_config() {
    echo "Configuration:"
    echo "  REPO_ROOT:     $REPO_ROOT"
    echo "  WORKTREE_BASE: $WORKTREE_BASE"
    echo "  MAIN_REPO:     $MAIN_REPO"
}

# Get the worktree index (0 for main, 1+ for worktrees)
get_worktree_index() {
    local current_path="$1"

    # If in main repo, index is 0
    if [[ "$current_path" == "$MAIN_REPO"* && "$current_path" != "$WORKTREE_BASE"* ]]; then
        echo 0
        return
    fi

    # Otherwise, calculate index from worktree name
    local worktree_name
    worktree_name=$(basename "$current_path")
    local index=1

    if [ -d "$WORKTREE_BASE" ]; then
        # Use a safe loop to handle spaces
        while IFS= read -r wt; do
            if [ "$wt" = "$worktree_name" ]; then
                echo "$index"
                return
            fi
            index=$((index + 1))
        done < <(ls -1 "$WORKTREE_BASE" 2>/dev/null | sort)
    fi

    # New worktree, assign next available index
    echo "$index"
}

# Calculate ports for a worktree
calculate_ports() {
    local worktree_path="$1"
    local index
    index=$(get_worktree_index "$worktree_path")

    local backend_port
    local frontend_port
    backend_port=$((BASE_BACKEND_PORT + (index * PORT_INCREMENT)))
    frontend_port=$((BASE_FRONTEND_PORT + (index * PORT_INCREMENT)))

    echo "$backend_port $frontend_port"
}

# Create .worktree.env file with port configuration
create_worktree_env() {
    local worktree_path="$1"
    local ports
    local backend_port
    local frontend_port
    ports=$(calculate_ports "$worktree_path")
    backend_port=$(echo "$ports" | cut -d' ' -f1)
    frontend_port=$(echo "$ports" | cut -d' ' -f2)
    local worktree_name
    worktree_name=$(basename "$worktree_path")

    cat > "$worktree_path/.worktree.env" << EOF
# Worktree-specific configuration
# Auto-generated by worktree-new.sh

WORKTREE_NAME=$worktree_name
BACKEND_PORT=$backend_port
FRONTEND_PORT=$frontend_port
VITE_API_URL=http://localhost:$backend_port/api/v1
EOF
    
    echo "Created .worktree.env with ports: backend=$backend_port, frontend=$frontend_port"
}

# Read port configuration for current directory
get_ports() {
    local script_dir
    script_dir="$(pwd)"
    local env_file=""
    
    # Look for .worktree.env in current dir or parent dirs
    local check_dir
    check_dir="$script_dir"
    while [ "$check_dir" != "/" ]; do
        if [ -f "$check_dir/.worktree.env" ]; then
            env_file="$check_dir/.worktree.env"
            break
        fi
        check_dir=$(dirname "$check_dir")
    done
    
    if [ -f "$env_file" ]; then
        # shellcheck disable=SC1090
        source "$env_file"
        echo "$BACKEND_PORT $FRONTEND_PORT"
    else
        # Default to main ports
        echo "$BASE_BACKEND_PORT $BASE_FRONTEND_PORT"
    fi
}

# Show all allocated ports
show_port_allocations() {
    local main_repo
    local worktree_base
    main_repo="$MAIN_REPO"
    worktree_base="$WORKTREE_BASE"

    echo "Port Allocations:"
    echo ""
    printf "%-30s %-12s %-12s\n" "Worktree" "Backend" "Frontend"
    printf "%-30s %-12s %-12s\n" "--------" "-------" "--------"
    
    # Main repo
    if [ -f "$main_repo/.worktree.env" ]; then
        # shellcheck disable=SC1090
        source "$main_repo/.worktree.env"
        printf "%-30s %-12s %-12s\n" "MAIN" "$BACKEND_PORT" "$FRONTEND_PORT"
    else
        printf "%-30s %-12s %-12s\n" "MAIN" "$BASE_BACKEND_PORT" "$BASE_FRONTEND_PORT"
    fi
    
    # Other worktrees
    if [ -d "$worktree_base" ]; then
        # iterate directories safely
        for wt_dir in "$worktree_base"/*/; do
            if [ -d "$wt_dir" ]; then
                wt_name=$(basename "$wt_dir")
                if [ -f "$wt_dir/.worktree.env" ]; then
                    # shellcheck disable=SC1090
                    source "$wt_dir/.worktree.env"
                    printf "%-30s %-12s %-12s\n" "$wt_name" "$BACKEND_PORT" "$FRONTEND_PORT"
                fi
            fi
        done
    fi
}

# If script is run directly, show port allocations
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Support --help
    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        echo "Usage: $0"
        echo "Show port allocations for main repo and worktrees."
        echo "Environment variables (optional): WORKTREE_BASE, MAIN_REPO"
        exit 0
    fi

    print_config
    show_port_allocations
fi
